In [228]:
import numpy as np
import pandas as pd

# Data Collection

In [229]:
df = pd.read_csv('/content/quikr_car.csv')
df.shape

(892, 6)

In [230]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

# Data Assessing

In [231]:
df['name'].duplicated().sum()

367

In [232]:
df['company'].unique()

array(['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'I', 'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Commercial', 'MARUTI', 'Force', 'Mercedes', 'Land', 'Yamaha',
       'selling', 'URJENT', 'Swift', 'Used', 'Jaguar', 'Jeep', 'tata',
       'Sale', 'very', 'Volvo', 'i', '2012', 'Well', 'all', '7', '9',
       'scratch', 'urgent', 'sell', 'TATA', 'Any', 'Tara'], dtype=object)

In [233]:
df['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [234]:
df['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [235]:
df['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [236]:
df['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [237]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

# Issue with Data  
## name column  
- name has 'Ta' and 'Tata' name car , should be remove

## company column
- 'MARUTI' should be replace with 'Maruti'
- 'tata' and 'TATA' should be replace with 'Tata'
- here too many non car campanies , remove it.  **car companies = ['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota','Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',    'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force',    'Mercedes', 'Land Rover', 'Jaguar', 'Jeep', 'Volvo']**  

## year column
- non numeric values should be removed  

## price column
- 'Ask For Price' and comma "," should be removed

## kms_driven column
- 'Petrol' , "," and " kms" should be removed
- here NAN value

## fuel_type column
- has NAN

# Data Cleaning

In [238]:
# backup the data set
backup = df.copy()

In [239]:
# replacing 'MARUTI' with 'Maruti'
df['company'] = df['company'].str.replace('MARUTI' , 'Maruti')

In [240]:
# replaceing 'tata' and 'TATA' with 'Tata'
df['company'] = df['company'].str.replace('tata' , 'Tata')
df['company'] = df['company'].str.replace('TATA' , 'Tata')

In [241]:
# removing non company names
car_companies = ['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota','Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen', 'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force', 'Mercedes', 'Land Rover', 'Jaguar', 'Jeep', 'Volvo']

df = df[df['company'].isin(car_companies)]

In [242]:
# checking...
df['company'].unique()

array(['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force',
       'Mercedes', 'Jaguar', 'Jeep', 'Volvo'], dtype=object)

In [243]:
# removing non year values
df = df[df['year'].str.isnumeric()]

In [244]:
# removing 'Ask For Price' and comma
df['Price'] = df[df['Price'] != 'Ask For Price' ]['Price'].str.replace(',' , '')

<ipython-input-244-00bba8742a93>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'] = df[df['Price'] != 'Ask For Price' ]['Price'].str.replace(',' , '')

In [245]:
df['kms_driven'] = df[df['kms_driven'] != 'Petrol']['kms_driven'].str.replace(' kms' , '')
df['kms_driven'] = df['kms_driven'].str.replace(',' ,'')

<ipython-input-245-ed45650b1b56>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['kms_driven'] = df[df['kms_driven'] != 'Petrol']['kms_driven'].str.replace(' kms' , '')
<ipython-input-245-ed45650b1b56>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['kms_driven'] = df['kms_driven'].str.replace(',' ,'')

In [246]:
# droping all NAN values
df.dropna(inplace =True)

<ipython-input-246-452a49741406>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace =True)

In [247]:
df.shape

(815, 6)

In [248]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000,Diesel

In [249]:
def get_short_name(line):
  temp = line.split(' ')

  if len(temp) < 3:
    return line
  else :
    return temp[0] + ' ' + temp[1] + ' ' + temp[2]

In [250]:
df['name'] = df['name'].apply(get_short_name)

<ipython-input-250-0a7a2f50c8f2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'] = df['name'].apply(get_short_name)

In [251]:
convert_dtype = {
    'name' : 'category',
    'company' : 'category',
    'year' : int,
    'Price' : int,
    'kms_driven' : int ,
    'fuel_type' : 'category'
}

df = df.astype(convert_dtype)

In [252]:
df.describe()

              year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.441718  4.096461e+05   46295.501840
std       4.004448  4.717751e+05   34313.741453
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  8.500003e+06  400000.000000

In [253]:
df = df[df['Price'] < 8e6]

In [254]:
# fixing indexing
df = df.reset_index(drop = True)

In [255]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
809      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
810          Tata Indica V2      Tata  2009  110000       30000    Diesel
811    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
812            Tata Zest XM      Tata  2018  260000       27000    Diesel
813      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[814 rows x 6 columns]

In [256]:
# saving cleaned data
df.to_csv('cleaned quikr_car.csv' , index = False)

# Model Building

In [257]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [258]:
df.head(1)

                  name  company  year  Price  kms_driven fuel_type
0  Hyundai Santro Xing  Hyundai  2007  80000       45000    Petrol

In [259]:
x = df[['name' , 'company' ,'fuel_type', 'year' , 'kms_driven']]
y = df['Price']

x.shape , y.shape

((814, 5), (814,))

In [260]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 2)

In [261]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(651, 5)
(163, 5)
(651,)
(163,)

In [262]:
encoder0 = LabelEncoder()
encoder1 = LabelEncoder()
encoder2 = LabelEncoder()

x_train.iloc[:,0] = encoder0.fit_transform(x_train.iloc[: ,0])
x_test.iloc[:,0] = encoder0.fit_transform(x_test.iloc[:,0])

x_train.iloc[:,1] = encoder1.fit_transform(x_train.iloc[: ,1])
x_test.iloc[:,1] = encoder1.fit_transform(x_test.iloc[:,1])

x_train.iloc[:,2] = encoder2.fit_transform(x_train.iloc[: ,2])
x_test.iloc[:,2] = encoder2.fit_transform(x_test.iloc[:,2])

In [263]:
x_train

     name  company  fuel_type  year  kms_driven
370   219       20          0  2012           0
272    15        2          2  2010       43000
800   142       12          0  2016      150000
602   218       20          0  2012       80000
333    84        9          2  2017        6821
..    ...      ...        ...   ...         ...
534   139       12          2  2014       37000
584    14        2          0  2011       56000
493    52        8          2  2014        6000
527   102        9          2  2010       10750
168   120       11          0  2015       97200

[651 rows x 5 columns]

In [264]:
x_test

     name  company  fuel_type  year  kms_driven
197    78       14          0  2012       65000
250     9        3          0  2014       50000
556    71       14          0  2016      104000
465    48        8          0  2016       55000
15      0        0          0  2014       16934
..    ...      ...        ...   ...         ...
603    50        8          0  2010       74000
231    11        4          0  2013       46000
205    41        7          0  2012       35000
537    43        8          2  2019        9800
743    42        7          0  2011       43000

[163 rows x 5 columns]

In [265]:
lr = LinearRegression()
lr.fit(x_train ,y_train)

LinearRegression()

In [266]:
y_pred = lr.predict(x_test)

In [267]:
r2_score(y_test , y_pred)

0.11093700980173826

In [268]:
score = []
for i in range(1000) :
  x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = i)

  encoder0 = LabelEncoder()
  encoder1 = LabelEncoder()
  encoder2 = LabelEncoder()

  x_train.iloc[:,0] = encoder0.fit_transform(x_train.iloc[: ,0])
  x_test.iloc[:,0] = encoder0.fit_transform(x_test.iloc[:,0])

  x_train.iloc[:,1] = encoder1.fit_transform(x_train.iloc[: ,1])
  x_test.iloc[:,1] = encoder1.fit_transform(x_test.iloc[:,1])

  x_train.iloc[:,2] = encoder2.fit_transform(x_train.iloc[: ,2])
  x_test.iloc[:,2] = encoder2.fit_transform(x_test.iloc[:,2])

  lr = LinearRegression()
  lr.fit(x_train ,y_train)

  y_pred = lr.predict(x_test)

  score.append(r2_score(y_test , y_pred))

In [269]:
temp = sorted(score , reverse=True)[:1][0]
temp

0.32521029884965524

In [270]:
index_for_high_accuracy = score.index(temp)
index_for_high_accuracy

921

In [271]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = index_for_high_accuracy )

encoder0 = LabelEncoder()
encoder1 = LabelEncoder()
encoder2 = LabelEncoder()

x_train.iloc[:,0] = encoder0.fit_transform(x_train.iloc[: ,0])
x_test.iloc[:,0] = encoder0.fit_transform(x_test.iloc[:,0])

x_train.iloc[:,1] = encoder1.fit_transform(x_train.iloc[: ,1])
x_test.iloc[:,1] = encoder1.fit_transform(x_test.iloc[:,1])

x_train.iloc[:,2] = encoder2.fit_transform(x_train.iloc[: ,2])
x_test.iloc[:,2] = encoder2.fit_transform(x_test.iloc[:,2])

lr = LinearRegression()
lr.fit(x_train ,y_train)

y_pred = lr.predict(x_test)

r2_score(y_test , y_pred)

0.32521029884965524

i am trying to find , how should i increase the accuracy...